name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build Docker Compose images
        run: docker compose build --no-cache

      - name: Start containers
        run: docker compose up -d

      - name: Wait for containers to be ready
        run: sleep 15

      - name: Check server container
        run: |
          curl --fail http://localhost:3000/check

      - name: Check client container
        run: |
          curl --fail http://localhost:4000

      - name: Show logs if failure
        if: failure()
        run: docker compose logs

      - name: Stop and remove containers
        run: docker compose down --volumes --remove-orphans
